### ISSUE TITLE
安卓手机安装完毕后 链接一直转圈圈

### ISSUE THREAD

**Issue by Jashon** [xapanyun/4gproxy#3]
安卓手机安装完毕后 链接一直转圈圈
无法使用
![WechatIMG274](https://user-images.githubusercontent.com/3355450/188420659-fc1993f5-3a08-4406-ac2b-45c918645e33.jpeg)

**Comment by xioxu** [comment]
Sorry, the app works in non-GFW env only.

**Comment by xapanyun** [comment]
Hi, the app works in non-GFW env only, thanks.
