### ISSUE TITLE
is Allproxy opensource?

### ISSUE THREAD

**Issue by Roeeklinger60** [xapanyun/4gproxy#5]
Hey,

in your project allproxy: https://github.com/xapanyun/4gproxy you did not include an opensource license, is allproxy open source? can I use it freely and modify it?

Apparently as per Github rules, if you do not include a license it is not considered opensource:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license#:~:text=From%20GitHub's%20licensing%20help%20page,derivative%20works%20from%20your%20work.

Thanks

**Comment by xioxu** [comment]
Hi, allproxy is not opensource, thanks.

**Comment by xapanyun** [comment]
Hi, allproxy is not open souce, thanks.
